---
title: "NLPStudio: Natural Language Processing Environment"
author: John James jjamse@datasciencesalon.org
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# NLPSTudio

## Overview
## Phase I
Classes and objects to perform primative tasks, any other composite tasks that are required to complete the data science capstone.   


# Design 

## NLPStudio

###
1. Can't remove a current lab. Client must assign a new lab current.  

## Labs
Labs are separate environments into which, documents exist.  One can create, enter and leave a lab. When one enters the lab, one can bring a corpus with them, or not.  Bringing in an existing corpus will copy it into the lab. The client can also build and manipulate corpora and documents. The objects in the lab are not effected by other objects in other labs.  Implementation note:
  1. This will require a new document class that provides the lab 

2. Each lab will have its own collection of documents, builders, etc...
3. There neednt' be the notion of a current lab. This was a relic of the principle of lab polymorphism. All objects (copora, files) were to be defined analogously to classes. They wouldn't be "instantiated" until they were assigned to a lab. There the objects could be manipulated and chained with other objects in the lab without effecting instances in other labs.  This would require    independent of the notion of a lab.  The assignment of an object to a lab would allow the client to make changes to that instance without effecting other


## Cache
1. All NLPStudio objects will be stored in cache.
2. Cache will be updated/created on every update/create operation
3. The cache will be an environment variable
4. When variables are created, the names given as a variable in the instantiation method will be assigned to the object. It will be cached under this name. 
5. When the package is loaded, the cache is read from file if available.  Objects in the cache but not in the current environment are loaded. If not available, load the package as normal.
6. Each instantiation / update method updates the variable in the current and cache environments. The cache environment is saved to disk on each change so that it mirrors the collection of NLPStudio objects in the current environment.
7. When the package is loaded, variables are loaded from cache.



